### PR TITLE
Fix infinite loop when walking zip directories

### PR DESCRIPTION
**Pull request by blachniet**
Need to skip the directory separator character when determining whether
the ZipEntry is a direct descendant of the current node.

Prior to these changes, walking a zip directory could result in an infinite loop and a `StackOverflowException`.

### CODE REVIEW

**Comment by tumtumtum** [comment]
Thank you!

**Comment by manuel-ornato** [comment]
Hi,
I still have this bug with the latest available Nuget binaries (1.2.1.124 from 2016-02-06).
I have a zip file with a 'Reports' folder inside and when I walk (or use GetChildren or any other way to enumerate) on the root folder -or even directly on the 'Reports' folder- it just returns the same'Reports' folder again and again.
Manuel

**Comment by tumtumtum** [comment]
Hmm could you put a unit test in if you have time?

**Comment by manuel-ornato** [comment]
Hi, I downloaded the sources but am having a hard time restoring NuGet packages from inside Visual Studio (no sources in the sources list, can't find packages). Is there a command line way?

**Pull request merged**
